gravitee-io/gravitee-cockpit-connectors

- .circleci/config.yml
- gravitee-cockpit-connectors-core/pom.xml
- gravitee-cockpit-connectors-ws/pom.xml
- pom.xml
Fixes gravitee-io/gravitee-cockpit#327
> chore(version): init version to 1.0.0-SNAPSHOT

- .circleci/config.yml
- pom.xml
Make CI push to both Artifactory & Nexus
> fix(): CI deploys on artifactory & nexus

- gravitee-cockpit-connectors-ws/src/main/java/io/gravitee/cockpit/connectors/ws/WebSocketCockpitConnector.java
- gravitee-cockpit-connectors-ws/src/main/java/io/gravitee/cockpit/connectors/ws/channel/ClientChannel.java
- gravitee-cockpit-connectors-ws/src/test/java/io/gravitee/cockpit/connectors/ws/channel/ClientChannelTest.java
- pom.xml
**Issue**
https://github.com/gravitee-io/gravitee-cockpit/issues/323
> Implement `sendCommand` in `WebSocketCockpitConnector`

- gravitee-cockpit-connectors-ws/src/main/java/io/gravitee/cockpit/connectors/ws/WebSocketCockpitConnector.java
- gravitee-cockpit-connectors-ws/src/main/java/io/gravitee/cockpit/connectors/ws/channel/ClientChannel.java
- gravitee-cockpit-connectors-ws/src/main/java/io/gravitee/cockpit/connectors/ws/channel/ClientChannelCloseHandler.java
- gravitee-cockpit-connectors-ws/src/test/java/io/gravitee/cockpit/connectors/ws/channel/ClientChannelTest.java
- pom.xml
https://github.com/gravitee-io/gravitee-cockpit/issues/455
> feat: close the connection on GoodbyeCommand

- gravitee-cockpit-connectors-ws/src/main/java/io/gravitee/cockpit/connectors/ws/channel/ClientChannel.java
gravitee-io/gravitee-cockpit#456
**Pre-requisite**
* You need this patch for Cockpit: https://github.com/gravitee-io/gravitee-cockpit/pull/462
* To test this one with AM, you need to update the `GoodbyeCommandHandler` to prevent deleting the installation
> feat: close connection if the current installation is deleted

- gravitee-cockpit-connectors-ws/src/main/java/io/gravitee/cockpit/connectors/ws/WebSocketCockpitConnector.java
- gravitee-cockpit-connectors-ws/src/main/java/io/gravitee/cockpit/connectors/ws/endpoints/WebSocketEndpoint.java
- gravitee-cockpit-connectors-ws/src/test/java/io/gravitee/cockpit/connectors/ws/endpoints/WebSocketEndpointTest.java
- pom.xml
https://github.com/gravitee-io/gravitee-cockpit/issues/449
> fix: avoid issue with / at the end of the URL

- gravitee-cockpit-connectors-core/pom.xml
- gravitee-cockpit-connectors-core/src/main/java/io/gravitee/cockpit/connectors/core/internal/CommandHandlerWrapper.java
- gravitee-cockpit-connectors-core/src/main/java/io/gravitee/cockpit/connectors/core/services/MonitoringCollectorService.java
- gravitee-cockpit-connectors-core/src/main/java/io/gravitee/cockpit/connectors/core/spring/CommandHandlersConfiguration.java
- gravitee-cockpit-connectors-core/src/main/java/io/gravitee/cockpit/connectors/core/spring/MonitoringCollectorConfiguration.java
- gravitee-cockpit-connectors-core/src/test/java/io/gravitee/cockpit/connectors/core/services/MonitoringCollectorServiceTest.java
- gravitee-cockpit-connectors-ws/pom.xml
- gravitee-cockpit-connectors-ws/src/main/java/io/gravitee/cockpit/connectors/ws/WebSocketCockpitConnector.java
- gravitee-cockpit-connectors-ws/src/main/java/io/gravitee/cockpit/connectors/ws/channel/ClientChannel.java
- gravitee-cockpit-connectors-ws/src/main/java/io/gravitee/cockpit/connectors/ws/spring/WebSocketConnectorConfiguration.java
- pom.xml
Related to gravitee-io/gravitee-cockpit#467
> feat(monitoring): monitoring data gathering

- gravitee-cockpit-connectors-core/src/main/java/io/gravitee/cockpit/connectors/core/spring/CommandHandlersConfiguration.java
- gravitee-cockpit-connectors-ws/pom.xml
- gravitee-cockpit-connectors-ws/src/main/java/io/gravitee/cockpit/connectors/ws/WebSocketCockpitConnector.java
- gravitee-cockpit-connectors-ws/src/main/java/io/gravitee/cockpit/connectors/ws/channel/ClientChannel.java
- gravitee-cockpit-connectors-ws/src/main/java/io/gravitee/cockpit/connectors/ws/spring/WebSocketConnectorConfiguration.java
- gravitee-cockpit-connectors-ws/src/test/java/io/gravitee/cockpit/connectors/ws/channel/ClientChannelTest.java
gravitee-io/gravitee-cockpit#534
> feat: close connection if the current installation is incompatible

- .circleci/config.yml
Here provided the Circle Ci Pipeline providing the following processes : 
* The Standalone Release
* The Standalone Release Replay
* Pull Requests with nexus staging on all branch but master
* nightly snapshot build n deploy to nexus everyday at midnight
All Those Processes a documented in detail at https://github.com/gravitee-io/kb/wiki/CICD:-Cockpit-Connectors
You will find there how to run dry run processes to test and validate this PR
> Cicd: new pipeline definition

- .circleci/config.yml
- gravitee-cockpit-connectors-core/src/main/java/io/gravitee/cockpit/connectors/core/services/MonitoringCollectorService.java
- gravitee-cockpit-connectors-core/src/test/java/io/gravitee/cockpit/connectors/core/services/MonitoringCollectorServiceTest.java
- gravitee-cockpit-connectors-ws/src/main/java/io/gravitee/cockpit/connectors/ws/channel/ClientChannel.java
> feat(): add MonitoringCommand

- gravitee-cockpit-connectors-core/pom.xml
- gravitee-cockpit-connectors-ws/pom.xml
- gravitee-cockpit-connectors-ws/src/main/java/io/gravitee/cockpit/connectors/ws/WebSocketCockpitConnector.java
- pom.xml
Related to gravitee-io/issues#5220
> chore(vertx4): move to gravitee-bom and use vertx4

- gravitee-cockpit-connectors-ws/src/main/java/io/gravitee/cockpit/connectors/ws/WebSocketCockpitConnector.java
- gravitee-cockpit-connectors-ws/src/main/java/io/gravitee/cockpit/connectors/ws/channel/ClientChannel.java
- gravitee-cockpit-connectors-ws/src/main/java/io/gravitee/cockpit/connectors/ws/spring/WebSocketConnectorConfiguration.java
- gravitee-cockpit-connectors-ws/src/test/java/io/gravitee/cockpit/connectors/ws/channel/ClientChannelTest.java
https://github.com/gravitee-io/gravitee-cockpit/issues/757
> feat: prevent failure when deserializing unknown properties

- gravitee-cockpit-connectors-core/src/main/java/io/gravitee/cockpit/connectors/core/services/AlertManagerService.java
- gravitee-cockpit-connectors-core/src/main/java/io/gravitee/cockpit/connectors/core/spring/AlertManagementConfiguration.java
- gravitee-cockpit-connectors-ws/src/main/java/io/gravitee/cockpit/connectors/ws/spring/WebSocketConnectorConfiguration.java
Related gravitee-io/gravitee-cockpit#744
> Register all triggers on connection

- gravitee-cockpit-connectors-core/src/main/java/io/gravitee/cockpit/connectors/core/services/AlertManagerService.java
Handle alert engine notification command
> feat: handle alert notification commands

- gravitee-cockpit-connectors-core/src/main/java/io/gravitee/cockpit/connectors/core/services/MonitoringCollectorService.java
- gravitee-cockpit-connectors-core/src/test/java/io/gravitee/cockpit/connectors/core/services/MonitoringCollectorServiceTest.java
https://github.com/gravitee-io/gravitee-cockpit/issues/1426
Fix sharding tags filtering in NodeCommand
> fix(nodeCommand): properly filter sharding tags

- gravitee-cockpit-connectors-core/src/main/java/io/gravitee/cockpit/connectors/core/services/MonitoringCollectorService.java
- gravitee-cockpit-connectors-core/src/test/java/io/gravitee/cockpit/connectors/core/services/MonitoringCollectorServiceTest.java
- pom.xml
**Issue**
https://github.com/gravitee-io/gravitee-cockpit/issues/2533
---
- use it directly by updating your project with version: `2.4.0-2533-remove-monitoring-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/cockpit/gravitee-cockpit-connectors/2.4.0-2533-remove-monitoring-SNAPSHOT/gravitee-cockpit-connectors-2.4.0-2533-remove-monitoring-SNAPSHOT.zip)
> feat: stop collecting node monitoring data

- gravitee-cockpit-connectors-core/src/main/java/io/gravitee/cockpit/connectors/core/services/MonitoringCollectorService.java
**Issue**
https://github.com/gravitee-io/gravitee-cockpit/issues/2378
Adding some delay to make sure there is an overlap between 2 node collections
---
- use it directly by updating your project with version: `2.4.9-2378-fix-node-collector-service-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/cockpit/gravitee-cockpit-connectors/2.4.9-2378-fix-node-collector-service-SNAPSHOT/gravitee-cockpit-connectors-2.4.9-2378-fix-node-collector-service-SNAPSHOT.zip)
> fix: add some overlap in the collector service

- gravitee-cockpit-connectors-ws/src/main/java/io/gravitee/cockpit/connectors/ws/channel/ClientChannel.java
- gravitee-cockpit-connectors-ws/src/test/java/io/gravitee/cockpit/connectors/ws/channel/ClientChannelTest.java
**Issue**
https://graviteedevops.atlassian.net/browse/COC-86
Use `binaryMessageHandler`and `writeBinaryMessage` to let Vert.x doing its magic to group multi-frame messages
---
- use it directly by updating your project with version: `2.5.4-coc86-handle-big-payload-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/cockpit/gravitee-cockpit-connectors/2.5.4-coc86-handle-big-payload-SNAPSHOT/gravitee-cockpit-connectors-2.5.4-coc86-handle-big-payload-SNAPSHOT.zip)
> fix: handle huge payload from cockpit controller

- gravitee-cockpit-connectors-core/src/main/java/io/gravitee/cockpit/connectors/core/services/MonitoringCollectorService.java
- gravitee-cockpit-connectors-core/src/main/java/io/gravitee/cockpit/connectors/core/spring/MonitoringCollectorConfiguration.java
- gravitee-cockpit-connectors-core/src/test/java/io/gravitee/cockpit/connectors/core/services/MonitoringCollectorServiceTest.java
- gravitee-cockpit-connectors-ws/src/main/java/io/gravitee/cockpit/connectors/ws/WebSocketCockpitConnector.java
- gravitee-cockpit-connectors-ws/src/main/java/io/gravitee/cockpit/connectors/ws/spring/CockpitConnectorConfiguration.java
- pom.xml
This PR fixes an issue with Node information which wasn't sent anymore.
---
- use it directly by updating your project with version: `5.0.4-fix-missing-node-info-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/cockpit/gravitee-cockpit-connectors/5.0.4-fix-missing-node-info-SNAPSHOT/gravitee-cockpit-connectors-5.0.4-fix-missing-node-info-SNAPSHOT.zip)
> fix: re-implement monitoring collector service

- README.md
Small PR to align the README with the new configuration.
---
- use it directly by updating your project with version: `5.0.5`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/cockpit/gravitee-cockpit-connectors/5.0.5/gravitee-cockpit-connectors-5.0.5.zip)
> doc: update README with new configuration

- gravitee-cockpit-connectors-ws/src/main/java/io/gravitee/cockpit/connectors/ws/WebSocketCockpitConnector.java
- gravitee-cockpit-connectors-ws/src/main/java/io/gravitee/cockpit/connectors/ws/spring/CockpitConnectorConfiguration.java
**Issue**
https://gravitee.atlassian.net/browse/CJ-1220
A small description of what you did in this PR.
---
- use it directly by updating your project with version: `5.0.13`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/cockpit/gravitee-cockpit-connectors/5.0.13/gravitee-cockpit-connectors-5.0.13.zip)
> chore: allow cloud instead of cockpit properties

- gravitee-cockpit-connectors-core/src/main/java/io/gravitee/cockpit/connectors/core/services/MonitoringCollectorService.java
- gravitee-cockpit-connectors-core/src/test/java/io/gravitee/cockpit/connectors/core/services/MonitoringCollectorServiceTest.java
- pom.xml
**Issue**
https://gravitee.atlassian.net/browse/CJ-2542
A small description of what you did in this PR.
---
- use it directly by updating your project with version: `5.1.0-cj-2542-gateway-technical-id-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/cockpit/gravitee-cockpit-connectors/5.1.0-cj-2542-gateway-technical-id-SNAPSHOT/gravitee-cockpit-connectors-5.1.0-cj-2542-gateway-technical-id-SNAPSHOT.zip)
> feat: add metadata property to NodeCommandPayload
