.circleci/config.yml

Circle CI Pipeline : 
* successfully mvn clean deploy, resulting with publishing to nexus sonatype snapshot repository :  see [this example execution](https://app.circleci.com/pipelines/github/gravitee-io/gravitee-cockpit-connectors/13/workflows/141480f4-9cd6-4d4a-9f68-00478ff52e1e/jobs/14)
* `pull_requests` job is removed, because now useful
* you have a cache management into pipeline 
* one commented step to add slack notifications : you will need Slack Oauth token to be able to use it (see comments in `.circleci/config.yml` 
* one commented step you can optionally use to persist any file, to the `persist_to_workspace` : 
* any file you save into the "Circle CI Pipeline Workspace" , is available for the next Pipeline execution
* e.g. if a zip file does not change, in the next pipeline …

feat.(cicd): build n deploy to nexus staging

---

gravitee-cockpit-connectors-core/pom.xml
gravitee-cockpit-connectors-ws/pom.xml
gravitee-cockpit-connectors-ws/src/main/java/io/gravitee/cockpit/connectors/ws/WebSocketCockpitConnector.java
gravitee-cockpit-connectors-ws/src/main/java/io/gravitee/cockpit/connectors/ws/endpoints/WebSocketEndpoint.java
gravitee-cockpit-connectors-ws/src/test/java/io/gravitee/cockpit/connectors/ws/endpoints/WebSocketEndpointTest.java
pom.xml

Patch cockpit-connection:1.0.0 to fix the issue with trailing / in the cockpit url.

[cockpit-connectors:1.0.x] fix: avoid issue with / at the end of the URL

---

gravitee-cockpit-connectors-core/src/main/java/io/gravitee/cockpit/connectors/core/services/MonitoringCollectorService.java
gravitee-cockpit-connectors-core/src/test/java/io/gravitee/cockpit/connectors/core/services/MonitoringCollectorServiceTest.java
gravitee-cockpit-connectors-ws/src/main/java/io/gravitee/cockpit/connectors/ws/WebSocketCockpitConnector.java
gravitee-cockpit-connectors-ws/src/main/java/io/gravitee/cockpit/connectors/ws/channel/ClientChannel.java
gravitee-cockpit-connectors-ws/src/main/java/io/gravitee/cockpit/connectors/ws/channel/ClientChannelEventHandler.java
gravitee-cockpit-connectors-ws/src/test/java/io/gravitee/cockpit/connectors/ws/channel/ClientChannelTest.java
pom.xml

Notifies listeners when Cockpit sends data to inform that the current installation instance becomes
a primary or a replica.
MonitoringCollectorService registers listeners on primary/replica to ensure only primary instance
sends monitoring data to Cockpit.
Related gravitee-io/gravitee-cockpit#335

feat: handle primary/replica on connector

---

gravitee-cockpit-connectors-ws/src/main/java/io/gravitee/cockpit/connectors/ws/channel/ClientChannel.java
gravitee-cockpit-connectors-ws/src/test/java/io/gravitee/cockpit/connectors/ws/channel/ClientChannelTest.java

Before this pull request, the connector was closing connection when receiving a message he is not able to decode.
We should simply ignore the message, and keep the connection open to handle compatibility in a smoother way.

feat: avoid closing connection on message decode exception

---

gravitee-cockpit-connectors-core/src/main/java/io/gravitee/cockpit/connectors/core/handlers/alert/AlertTriggerCommandHandler.java
gravitee-cockpit-connectors-core/src/main/java/io/gravitee/cockpit/connectors/core/spring/CommandHandlersConfiguration.java
gravitee-cockpit-connectors-core/src/test/java/io/gravitee/cockpit/connectors/core/handlers/alert/AlertTriggerCommandHandlerTest.java
gravitee-cockpit-connectors-ws/src/main/java/io/gravitee/cockpit/connectors/ws/spring/WebSocketConnectorConfiguration.java
pom.xml

https://github.com/gravitee-io/gravitee-cockpit/issues/651
How to test?
- Need an AM EE
- Get the alert-engine connector from Artifactory (gravitee-ae-connectors-ws-1.4.0-20210720.000731-40.zip)
- Copy the connector in your GRAVITEE_HOME/plugins
- Start AM EE with the following env variables:
```
gravitee_alerts_alert-engine_enabled=true
gravitee_alerts_alert-engine_ws_discovery=true
gravitee_alerts_alert-engine_ws_endpoints_0=http://cockpit-dev-ae.cloud.gravitee.io
gravitee_alerts_alert-engine_ws_security_username=admin
gravitee_alerts_alert-engine_ws_security_password=adminadmin
```
- In Cockpit, create a trigger and check Alert Engine logs for
```
gravitee-ae-engine-7bb9965766-4ngsx gravitee-ae-engine 14:05:01.019 [hz.nifty_thompson.event-2] [] INFO  c.g.a.e.a.drools.DroolsAlertEngine …
```

feat: create trigger in ae

---

.circleci/config.yml

Ci-dessous le lien vers la Pipeline de la standalone_release_replay en mode dry run, avec le job qui fait le package bundle, et dépose les fichiers zip de la version 2.0.0 dans le gravitee.download 
* test no. 1 : https://app.circleci.com/pipelines/github/gravitee-io/gravitee-cockpit-connectors/391/workflows/e1270a31-366d-48fc-8323-b673c9a1ba02
* test no. 2 : https://app.circleci.com/pipelines/github/gravitee-io/gravitee-cockpit-connectors/402/workflows/42c6eb29-f6c4-415e-be2a-454c48a50cd1
Ci-dessous le lien vers les fichiers zip deposés en mode dry-run :
https://gravitee-dry-releases-downloads.cellar-c2.services.clever-cloud.com/index.html#graviteeio-cockpit/plugins/connectors/gravitee-connector-connectors-ws/
Ci-dessous le lien vers les fichiers zip deposés dans le gravitee.downloads : …

package bundle

---

.github/CODEOWNERS
.github/renovate.json

Description
Setup Renovate to keep our dependencies up to date.
Override #42 as Renovate bot automatically force push in the branch of the PR 🙃 so I can't rename the commit.

Initialize renovate

---

gravitee-cockpit-connectors-ws/src/main/java/io/gravitee/cockpit/connectors/ws/http/HttpClientConfiguration.java

https://github.com/gravitee-io/gravitee-node/pull/98 introduces a fix for properties loading.
Unfortunately, the fix is not enough: it will search property using their exact name whereas it should also search with alternative structure:
`cockpit.ws.endpoints[0]` should be equivalent to `cockpit_ws_endpoints_0`.
A fix will be done in gravitee-node. However, AM team would avoid upgrading gravitee-node, therefore, we provide a fix to avoid that.

fix: change property name used to get endpoints

---

.github/pull_request_template.md
gravitee-cockpit-connectors-core/pom.xml
gravitee-cockpit-connectors-ws/pom.xml

**Issue**
https://github.com/gravitee-io/gravitee-cockpit-connectors/issues/127
Remove missing `SNAPSHOT` from maven sub-modules
---
- use it directly by updating your project with version: `2.3.1-fix-release-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/cockpit/gravitee-cockpit-connectors/2.3.1-fix-release-SNAPSHOT/gravitee-cockpit-connectors-2.3.1-fix-release-SNAPSHOT.zip)

fix(ci): remove SNAPSHOT from submodules

---

gravitee-cockpit-connectors-ws/pom.xml

The connector should be published in the list of APIM plugins ([here](https://download.gravitee.io/#graviteeio-apim/plugins/connectors/gravitee-cockpit-connectors-ws/)), not Cockpit ([not here](https://download.gravitee.io/#graviteeio-cockpit/plugins/connectors/gravitee-cockpit-connectors-ws/))
---
- use it directly by updating your project with version: `2.3.1`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/cockpit/gravitee-cockpit-connectors/2.3.1/gravitee-cockpit-connectors-2.3.1.zip)

chore: update plugin publish folder

---

gravitee-cockpit-connectors-ws/pom.xml

**Issue**
N/A
Change the publication folder so cockpit connectors are deployed here https://download.gravitee.io/#graviteeio-cockpit/plugins/connectors/gravitee-connector-connectors-ws/
---
- use it directly by updating your project with version: `2.3.5`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/cockpit/gravitee-cockpit-connectors/2.3.5/gravitee-cockpit-connectors-2.3.5.zip)

ci: change the publication folder on download website

---

gravitee-cockpit-connectors-ws/src/main/java/io/gravitee/cockpit/connectors/ws/WebSocketCockpitConnector.java
gravitee-cockpit-connectors-ws/src/main/java/io/gravitee/cockpit/connectors/ws/channel/ClientChannel.java

**Issue**
https://graviteedevops.atlassian.net/browse/COC-117
Gravitee platform does not allow catching the shutdown of the node to stop plugins. That's why we are using a Shutdown Hook to stop the connectors
---
- use it directly by updating your project with version: `2.6.0-shutdown-hook-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/cockpit/gravitee-cockpit-connectors/2.6.0-shutdown-hook-SNAPSHOT/gravitee-cockpit-connectors-2.6.0-shutdown-hook-SNAPSHOT.zip)

feat: handle a graceful shutdown

---

.circleci/config.yml
pom.xml

Due to an issue while using this connector with latest apim, gravitee-node has to be upgraded.
```
10:25:44.999 [cockpit-monitoring-collector-1] ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task
java.lang.IncompatibleClassChangeError: Found interface io.gravitee.node.monitoring.NodeMonitoringService, but class was expected
at io.gravitee.cockpit.connectors.core.services.MonitoringCollectorService.collectAndSend(MonitoringCollectorService.java:103)
at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:96)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown …
```

fix: bump gravitee node version

---

gravitee-cockpit-connectors-ws/src/main/java/io/gravitee/cockpit/connectors/ws/http/HttpClientConfiguration.java
gravitee-cockpit-connectors-ws/src/main/java/io/gravitee/cockpit/connectors/ws/http/HttpClientFactory.java

**Issue**
https://gravitee.atlassian.net/browse/APIM-2117
https://github.com/gravitee-io/issues/issues/9110
Also, change the default value of `maxWebSocketMessageSize` to 13MB instead of 262KB.
See https://github.com/gravitee-io/gravitee-cockpit/pull/3750 for more info about the context.
---
- use it directly by updating your project with version: `2.6.1-COC-360-handle-big-ws-messages-2-x-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/cockpit/gravitee-cockpit-connectors/2.6.1-COC-360-handle-big-ws-messages-2-x-SNAPSHOT/gravitee-cockpit-connectors-2.6 …

[2.x] Add configuration for WS max frame and message sizes

---

gravitee-cockpit-connectors-ws/src/main/java/io/gravitee/cockpit/connectors/ws/http/HttpClientConfiguration.java
gravitee-cockpit-connectors-ws/src/main/java/io/gravitee/cockpit/connectors/ws/http/HttpClientFactory.java

**Issue**
https://gravitee.atlassian.net/browse/APIM-2117
https://github.com/gravitee-io/issues/issues/9110
Cherry pick of https://github.com/gravitee-io/gravitee-cockpit-connectors/pull/208 on the `master` branch
> Also, change the default value of `maxWebSocketMessageSize` to 13MB instead of 262KB.
> See https://github.com/gravitee-io/gravitee-cockpit/pull/3750 for more info about the context.
---
- use it directly by updating your project with version: `4.0.1-COC-360-handle-big-ws-messages-master-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/cock …

[master] Add configuration for WS max frame and message sizes

---

gravitee-cockpit-connectors-ws/src/main/java/io/gravitee/cockpit/connectors/ws/http/HttpClientConfiguration.java
gravitee-cockpit-connectors-ws/src/main/java/io/gravitee/cockpit/connectors/ws/http/HttpClientFactory.java

**Issue**
https://gravitee.atlassian.net/browse/APIM-2117
https://github.com/gravitee-io/issues/issues/9110
Cherry pick of https://github.com/gravitee-io/gravitee-cockpit-connectors/pull/208 on the `3.x` branch
> Also, change the default value of `maxWebSocketMessageSize` to 13MB instead of 262KB.
> See https://github.com/gravitee-io/gravitee-cockpit/pull/3750 for more info about the context.
---
- use it directly by updating your project with version: `3.0.4-COC-360-handle-big-ws-messages-3-x-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/cockpit/gr …

[3.x] Add configuration for WS max frame and message sizes

---

pom.xml

updated cockpit api, gravitee-node and gravitee-plugin version
---
- use it directly by updating your project with version: `4.0.2-coc-2174-update-versions-in-alpha-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/cockpit/gravitee-cockpit-connectors/4.0.2-coc-2174-update-versions-in-alpha-SNAPSHOT/gravitee-cockpit-connectors-4.0.2-coc-2174-update-versions-in-alpha-SNAPSHOT.zip)

coc-2174 update versions in alpha

---

gravitee-cockpit-connectors-core/src/main/java/io/gravitee/cockpit/connectors/core/spring/MonitoringCollectorConfiguration.java

Since Spring 6.1.x, LocalVariableTableParameterNameDiscoverer has been removed
this may cause trouble during injection if ObjectMapper is known twice with different name accross the SpringContext hierarchy
to avoid, this as the ObjectMapper is named explicitly in the Configuration bean we use it
---
- use it directly by updating your project with version: `4.0.3-fix-spring-qualifier-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/cockpit/gravitee-cockpit-connectors/4.0.3-fix-spring-qualifier-SNAPSHOT/gravitee-cockpit-connectors-4.0.3-fix-spring-qualifier-SNAPSHOT.zip …

fix: Enforce the cockpitObjectMapper qualifier for Spring 6.1.x+

---

.circleci/config.yml
.github/renovate.json
gravitee-cockpit-connectors-core/pom.xml
gravitee-cockpit-connectors-core/src/main/java/io/gravitee/cockpit/connectors/core/internal/CommandHandlerWrapper.java
gravitee-cockpit-connectors-core/src/main/java/io/gravitee/cockpit/connectors/core/services/MonitoringCollectorService.java
gravitee-cockpit-connectors-core/src/main/java/io/gravitee/cockpit/connectors/core/spring/CommandHandlersConfiguration.java
gravitee-cockpit-connectors-core/src/main/java/io/gravitee/cockpit/connectors/core/spring/MonitoringCollectorConfiguration.java
gravitee-cockpit-connectors-core/src/test/java/io/gravitee/cockpit/connectors/core/services/MonitoringCollectorServiceTest.java
gravitee-cockpit-connectors-ws/pom.xml
gravitee-cockpit-connectors-ws/src/main/assembly/plugin-assembly.xml
gravitee-cockpit-connectors-ws/src/main/java/io/gravitee/cockpit/connectors/ws/WebSocketCockpitConnector.java
gravitee-cockpit-connectors-ws/src/main/java/io/gravitee/cockpit/connectors/ws/channel/ClientChannel.java
gravitee-cockpit-connectors-ws/src/main/java/io/gravitee/cockpit/connectors/ws/channel/ClientChannelEventHandler.java
gravitee-cockpit-connectors-ws/src/main/java/io/gravitee/cockpit/connectors/ws/endpoints/WebSocketEndpoint.java
gravitee-cockpit-connectors-ws/src/main/java/io/gravitee/cockpit/connectors/ws/exceptions/ChannelClosedException.java
gravitee-cockpit-connectors-ws/src/main/java/io/gravitee/cockpit/connectors/ws/http/HttpClientConfiguration.java
gravitee-cockpit-connectors-ws/src/main/java/io/gravitee/cockpit/connectors/ws/http/HttpClientFactory.java
gravitee-cockpit-connectors-ws/src/main/java/io/gravitee/cockpit/connectors/ws/spring/WebSocketConnectorConfiguration.java
gravitee-cockpit-connectors-ws/src/test/java/io/gravitee/cockpit/connectors/ws/channel/ClientChannelTest.java
gravitee-cockpit-connectors-ws/src/test/java/io/gravitee/cockpit/connectors/ws/endpoints/WebSocketEndpointTest.java
pom.xml

Upgrade gravitee dependencies
The PR also adjust license declaration and code formation according to latest maven plugins' configurations
---
- use it directly by updating your project with version: `4.0.4-chore-upgrade-gravitee-deps-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/cockpit/gravitee-cockpit-connectors/4.0.4-chore-upgrade-gravitee-deps-SNAPSHOT/gravitee-cockpit-connectors-4.0.4-chore-upgrade-gravitee-deps-SNAPSHOT.zip)

fix(chore): update gravitee dependencies

---

gravitee-cockpit-connectors-ws/src/main/java/io/gravitee/cockpit/connectors/ws/WebSocketCockpitConnector.java

Since the introduction of Integration Controller in APIM, we can see the following error
`No qualifying bean of type 'io.gravitee.exchange.api.websocket.command.ExchangeSerDe' available: expected single matching bean but found 2: cockpitExchangeSerDe,integrationExchangeSerDe`
which was due to the extra contructor which applied different bean injection.
---
- use it directly by updating your project with version: `5.0.3-fix-cockpit-connector-init-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/cockpit/gravitee-cockpit-connectors/ …

fix: update ExchangeSerDe interface to help Spring initialization

---

pom.xml

**Issue**
https://github.com/gravitee-io/gravitee-cockpit-connectors/issues/XXXXX
A small description of what you did in this PR.
---
- use it directly by updating your project with version: `5.0.9-bump-gravitee-exchange-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/cockpit/gravitee-cockpit-connectors/5.0.9-bump-gravitee-exchange-SNAPSHOT/gravitee-cockpit-connectors-5.0.9-bump-gravitee-exchange-SNAPSHOT.zip)

fix(deps): bump gravitee-cockpit-api to 3.0.18

---

pom.xml

**Issue**
https://gravitee.atlassian.net/browse/ARCHI-391
A small description of what you did in this PR.
---
- use it directly by updating your project with version: `5.0.26-archi-391-update-exchange-version-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/cockpit/gravitee-cockpit-connectors/5.0.26-archi-391-update-exchange-version-SNAPSHOT/gravitee-cockpit-connectors-5.0.26-archi-391-update-exchange-version-SNAPSHOT.zip)

fix: bump exchange framework version

---

gravitee-cockpit-connectors-core/src/main/java/io/gravitee/cockpit/connectors/core/services/MonitoringCollectorService.java
pom.xml

**Issue**
https://gravitee.atlassian.net/browse/ARCHI-391
See also https://github.com/gravitee-io/gravitee-exchange/blob/main/CHANGELOG.md#180-2024-07-25
---
- use it directly by updating your project with version: `5.0.27-archi-391-handle-command-error-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/cockpit/gravitee-cockpit-connectors/5.0.27-archi-391-handle-command-error-SNAPSHOT/gravitee-cockpit-connectors-5.0.27-archi-391-handle-command-error-SNAPSHOT.zip)

Archi 391 handle command error

---

pom.xml

https://gravitee.atlassian.net/browse/ARCHI-391
See https://github.com/gravitee-io/gravitee-exchange/blob/main/CHANGELOG.md#182-2024-07-26
---
- use it directly by updating your project with version: `5.0.28-archi-391-handle-thread-blocked-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/cockpit/gravitee-cockpit-connectors/5.0.28-archi-391-handle-thread-blocked-SNAPSHOT/gravitee-cockpit-connectors-5.0.28-archi-391-handle-thread-blocked-SNAPSHOT.zip)

fix: bump exchange framework to 1.8.2

---

pom.xml

**Issue**
https://gravitee.atlassian.net/browse/APIM-6226
Let apim choose the version of gravitee-exchange-api without interference from others dependencies
---
- use it directly by updating your project with version: `5.0.30`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/cockpit/gravitee-cockpit-connectors/5.0.30/gravitee-cockpit-connectors-5.0.30.zip)

chore(deps): declare gravitee-exchange-api as provided
